Repository StylishThemes/GitHub-Dark, pull requests merged in 2019-01, with the labels that each got.

#817 fix: bottom border fixes #814
  github-dark.css
Labels: bug fix :bug: :wrench:

#816 fix: overdue milestone warning text fixes #765
  github-dark.css
Labels: bug fix :bug: :wrench:

#831 Add Font Size choice
  Gruntfile.js
  defaults.json
  github-dark.css
  github-dark.user.css
  index.html
  tools/usercss-template.css
Labels: enhancement ⭐

#826 Remove scrollbars styling fixes #820
  github-dark.css
Labels: enhancement ⭐, feedback needed 🤔

#835 fix: typos in documentation
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  README.md
Labels: enhancement ⭐
